---
title: "Infrastructure requirements for research and teaching"
subtitle: "<br>"
author: "Dr Victor Maus<br>.font80[Vienna University of Economics and Business]<br>.font80[victor.maus@wu.ac.at]<br>.font80[<a href='https://www.victor-maus.com'>www.victor-maus.com</a>]"
date: ".left[.font80[May 26, 2021]]"
output: 
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    self_contained: true
    css: [default, metropolis, metropolis-fonts, libs/my.css, libs/tachyons-min.css]
    nature:
      beforeInit: "libs/my-macros.js"
      ratio: '16:9'
      highlightStyle: atom-one-light
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
editor_options: 
  chunk_output_type: console
---
class: clear
```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
```

---
class: clear

.pull-left[

.center.bg-washed-blue.b--dark-blue.ba.bw2.br3.shadow-5.mb1[**Hardware**]
  
  - **Access to HPC CPU and GPU clusters**. The cluster will be used to scale applications to large geographical areas. Access to a GPU cluster is critical for state-of-the-art ML methods. According to <https://hpc-unibe-ch.github.io> UBELIX would proved sufficient resources, besides having a pretty cool name.

  - **A data server minimum 12 cores, 64GB RAM, 10TB storage capacity.** The server will host Geoserver and Rstudio server. It will be used for development and test of algorithms, small scale analysis, geodata storage persistent storage and share. The storage could be combined with UBELIX storage, but technical details need to be discussed.

  - **A laptop** Linux operating system and switch of open source GIS software.
  
  - **Infrastructure for teaching** Computer lab and access to HPC (CPU and GPU).

]

.pull-right[

.center.bg-washed-blue.b--dark-blue.ba.bw2.br3.shadow-5.mb1[**Software**]

  - Linux operating system and set of open source software, R, Python, GDAL, PostgreSQL+PostGIS, QGIS, etc.

  - Overleaf license for online collaborative Latex witting. According to <https://www.overleaf.com/edu/unibe> University of Bern already provides the license for staff and students. Is it correct?

.center.bg-washed-blue.b--dark-blue.ba.bw2.br3.shadow-5.mb1[**Questions**]
  
  - Does GIUB has its own data infrastructure? 
  
  - UBELIX team charges for additional storage. Are there additional costs for processing in UBELIX?
  
  - Can the UBELIX data shares be mounted in other servers in the University's network?

  - Does University of Bern provide resources to access other could processing facilities, e.g. Google and AWS?

]
